name: Run Cypress Tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        name: Install modules
        uses: npi ci

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          headless: true
          build: yarn build
          start: npm run dev
          wait-on: "http://localhost:3000"