name: Cypress Tests

on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run Cypress tests
      run: npm run cy:run

    - name: Upload Cypress Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: cypress/screenshots

    - name: Upload Cypress Results
      uses: actions/upload-artifact@v2
      with:
        name: cypress-results
        path: cypress/results

